project_id = "obbvohtcglpfnqbthnga"

[functions.confirm-quote]
verify_jwt = false

[functions.update-ups-tracking]
verify_jwt = false

[functions.log-admin-login]
verify_jwt = true

[functions.send-security-alert]
verify_jwt = true

[functions.send-waitlist-confirmation]
verify_jwt = false

[functions.send-waitlist-approval]
verify_jwt = true
